### ISSUE TITLE
make a project page for Greener Greenhouses

### ISSUE THREAD

**Issue by cjosephson** [jlab-sensing/sensors.soe.ucsc.edu-old-fork#15]
Greener Greenhouses is missing from our projects page.

<img width="900" alt="image" src="https://github.com/jlab-sensing/sensors.soe.ucsc.edu/assets/707398/afaf98ff-004e-4332-893f-7d83e8028e18">

Please leverage the proposal written earlier this year to write a brief overview of the project, and be sure to include the photo Sylvie sent us. 

Please do this by March 17 if possible.

**Comment by MatthewKalt** [comment]
Pull request submitted to Aaron for review and publishing
